import pyrosetta
from pyrosetta import *
import rosetta

init()

protein = 'T0953s1'

seq_T0955 = 'SQETRKKCTEMKKKFKNCEVRCDESNHCVEVRCSDTKYTLC'
seq_T0953s1 = 'GALGSASIAIGDNDTGLRWGGDGIVQIVANNAIVGGWNSTDIFTEAGKHITSNGNLNQWGGGAIYCRDLNVS'
seq_T0974s1 = 'MSYDYSSLLGKITEKCGTQYNFAIAMGLSERTVSLKLNDKVTWKDDEILKAVHVLELNPQDIPKYFFNAKVH'
seq_T1006 = 'DIYGDEITAVVSKIENVKGISQLKTRHIGQKIWAELNILVDPDSTIVQGETIASRVKKALTEQIRDIERVVVHFEPARK'
seq_T1008 = 'TDELLERLRQLFEELHERGTEIVVEVHINGERDEIRVRNISKEELKKLLERIREKIEREGSSEVEVNVHSGGQTWTFNEK'
seq_T0967 = 'EDYIEAIANVLEKTPSISDVKDIIARELGQVLEFEIDLYVPPDITVTTGERIKKEVNQIIKEIVDRKSTVKVRLFAAQEEL'
seq_T1072s2 = 'GSMGKDEALEKDLNDVSKEINLMLSTYAKLLSERAAVDASYIDEIDELFKEANAIENFLIQKREFLRQR'
seq_T1046s1 = 'MNVDPHFDKFMESGIRHVYMLFENKSVESSEQFYSFMRTTYKNDPCSSDFECIERGAEMAQSYARIMNIKLETE'
seq_T0884 = 'RGPSNGQSVLENSVQVKETSPRRVSVDPQTGEFVVFDRTLGDVYHGHVRAWKDLTSDMQNALVRGGYVDRKGNPK'





pose = pyrosetta.pose_from_pdb(f'../out/{protein}/pre_relaxation_altmh.pdb')

# mutate ALA back to GLY
for i,a in enumerate(seq):
    if a == 'G':
        mutator = rosetta.protocols.simple_moves.MutateResidue(i+1,'GLY')
        mutator.apply(pose)
        print('mutation: A%dG'%(i+1))    
pose.dump_pdb(f'../out/{protein}/mutated_back_alt.pdb')
